"use client";

import { useState } from "react";
import { Button } from "@web-containers/components/ui/button";
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@web-containers/components/ui/tabs";
import { Plus } from "lucide-react";
import IntegrationAutogeneratedTab from "./api-tab/integration-autogenerated-table";
import { CreateApiModal } from "./api-tab/create-api-modal";
import { CreateLLMModal } from "./llms-tab/create-llm-modal";
import IntegrationLLMsTab from "./llms-tab/integration-llms-tab";
import { CreateDataSourceModal } from "./data-sources-tab/create-data-source-modal";
import IntegrationDataSourcesTab from "./data-sources-tab/integration-data-sources-tab";

export default function IntegrationsTab({
  tenantKey,
  username,
}: {
  tenantKey: string;
  username: string;
}) {
  const [activeTab, setActiveTab] = useState("llms"); //useState("generated")

  const [showCreateApiModal, setShowCreateApiModal] = useState(false);
  const [showCreateLLMModal, setShowCreateLLMModal] = useState(false);
  const [showCreateDataSourceModal, setShowCreateDataSourceModal] = useState(false);

  function closeCreateApiModal() {
    setShowCreateApiModal(false);
  }

  function openCreateApiModal() {
    setShowCreateApiModal(true);
  }

  function closeCreateLLMModal() {
    setShowCreateLLMModal(false);
  }

  function openCreateLLMModal() {
    setShowCreateLLMModal(true);
  }

  function closeCreateDataSourceModal() {
    setShowCreateDataSourceModal(false);
  }

  function openCreateDataSourceModal() {
    setShowCreateDataSourceModal(true);
  }

  return (
    <div className="container mx-auto max-w-7xl !mt-0">
      <Tabs
        value={activeTab}
        onValueChange={setActiveTab}
        className="w-full px-2 sm:px-0"
      >
        <div className="flex flex-col gap-3 sm:flex-row sm:justify-between sm:items-center mb-6">
          <TabsList className="sm:grid sm:w-fit sm:grid-cols-3 h-auto sm:h-[35px] gap-2 sm:gap-0">
            <TabsTrigger
              value="llms"
              className={activeTab === "llms" ? "w-full" : undefined}
            >
              LLMs
            </TabsTrigger>
            <TabsTrigger
              value="data-sources"
              className={activeTab === "data-sources" ? "w-full" : undefined}
            >
              Data Sources
            </TabsTrigger>
            <TabsTrigger
              value="generated"
              className={activeTab === "generated" ? "w-full" : undefined}
            >
              APIs
            </TabsTrigger>
          </TabsList>
          <div className="flex gap-2 w-full sm:w-auto">
            {activeTab === "llms" && (
              <Button
                className="bg-gradient-to-r from-[#2563EB] to-[#93C5FD] hover:opacity-90 text-white h-[35px] w-full sm:w-auto"
                onClick={openCreateLLMModal}
              >
                <Plus className="w-4 h-4 mr-2" />
                Add LLM
              </Button>
            )}
            {activeTab === "data-sources" && (
              <Button
                className="bg-gradient-to-r from-[#2563EB] to-[#93C5FD] hover:opacity-90 text-white h-[35px] w-full sm:w-auto"
                onClick={openCreateDataSourceModal}
              >
                <Plus className="w-4 h-4 mr-2" />
                Add Data Source
              </Button>
            )}
            {activeTab === "generated" && (
              <Button
                className="bg-gradient-to-r from-[#2563EB] to-[#93C5FD] hover:opacity-90 text-white h-[35px] w-full sm:w-auto"
                onClick={openCreateApiModal}
              >
                <Plus className="w-4 h-4 mr-2" />
                Add API
              </Button>
            )}
          </div>
        </div>

        <TabsContent value="generated" className="space-y-4">
          <IntegrationAutogeneratedTab tenantKey={tenantKey} />
        </TabsContent>

        <TabsContent value="llms" className="space-y-4">
          <IntegrationLLMsTab tenantKey={tenantKey} />
        </TabsContent>

        <TabsContent value="data-sources" className="space-y-4">
          <IntegrationDataSourcesTab tenantKey={tenantKey} />
        </TabsContent>
      </Tabs>
      <CreateApiModal
        isOpen={showCreateApiModal}
        onClose={closeCreateApiModal}
        tenantKey={tenantKey}
        username={username}
      />
      <CreateLLMModal
        isOpen={showCreateLLMModal}
        onClose={closeCreateLLMModal}
        tenantKey={tenantKey}
      />
      <CreateDataSourceModal
        isOpen={showCreateDataSourceModal}
        onClose={closeCreateDataSourceModal}
        tenantKey={tenantKey}
      />
    </div>
  );
}
