import { Trash } from 'lucide-react';
import { format } from 'date-fns';

import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@web-containers/components/ui/table';
import { Button } from '@web-containers/components/ui/button';
import { useGetApiKeysQuery } from '@iblai/data-layer';
import { ApiKey, DeleteApiModal } from './delete-api-modal';
import React from 'react';
import { Card, CardContent, CardDescription, CardHeader } from '@web-containers/components/ui/card';

export default function IntegrationAutogeneratedTab({ tenantKey }: { tenantKey: string }) {
  const { data: apiKeys, isLoading: isApiKeysLoading } = useGetApiKeysQuery({
    platformKey: tenantKey,
  });

  const [apiKeyToDelete, setApiKeyToDelete] = React.useState<ApiKey | null>(null);

  function closeDeleteApiModal() {
    setApiKeyToDelete(null);
  }

  function openDeleteApiModal(apiKey: ApiKey) {
    setApiKeyToDelete(apiKey);
  }

  return (
    <>
      <Card style={{ borderColor: 'oklch(.922 0 0)' }}>
        <CardHeader>
          <div className="flex items-start gap-2">
            <CardDescription>
              These are authentication keys that you've generated for external applications to
              authenticate with your service. Keys are displayed only once when generated.
            </CardDescription>
          </div>
        </CardHeader>
        <CardContent>
          <Table className="w-full">
            <TableHeader>
              <TableRow style={{ borderColor: 'oklch(.922 0 0)' }}>
                <TableHead className="p-2 text-left text-sm text-[#646464]">NAME</TableHead>
                <TableHead className="p-2 text-left text-sm text-[#646464]">CREATED</TableHead>
                <TableHead className="p-2 text-left text-sm text-[#646464]">EXPIRES</TableHead>
                <TableHead className="p-2 text-left text-sm text-[#646464]"></TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {isApiKeysLoading ? (
                <TableRow style={{ borderColor: 'oklch(.922 0 0)' }}>
                  <TableCell colSpan={4} className="p-4 sm:text-center text-sm text-gray-500">
                    Loading...
                  </TableCell>
                </TableRow>
              ) : apiKeys?.length === 0 ? (
                <TableRow style={{ borderColor: 'oklch(.922 0 0)' }}>
                  <TableCell colSpan={4} className="p-4 sm:text-center text-sm text-gray-500">
                    No API keys found
                  </TableCell>
                </TableRow>
              ) : (
                apiKeys?.map((apiKey) => (
                  <TableRow
                    key={apiKey.name}
                    className="text-sm"
                    style={{ borderColor: 'oklch(.922 0 0)' }}
                  >
                    <TableCell className="p-2 whitespace-nowrap text-[#646464]">
                      {apiKey.name}
                    </TableCell>
                    <TableCell className="p-2 whitespace-nowrap text-[#646464]">
                      {apiKey.created ? format(apiKey.created, 'PPP') : 'N/A'}
                    </TableCell>
                    <TableCell className="p-2 whitespace-nowrap text-[#646464]">
                      {apiKey.expires ? format(apiKey.expires, 'PPP') : 'N/A'}
                    </TableCell>
                    <TableCell className="p-2">
                      <Button
                        variant="ghost"
                        size="sm"
                        className="cursor-pointer"
                        onClick={() => openDeleteApiModal({ name: apiKey.name })}
                      >
                        <Trash className="h-4 w-4" />
                      </Button>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
      {apiKeyToDelete && (
        <DeleteApiModal
          isOpen={!!apiKeyToDelete}
          onClose={closeDeleteApiModal}
          apiKey={apiKeyToDelete}
          tenantKey={tenantKey}
        />
      )}
    </>
  );
}
